# -*- coding: utf-8 -*-
"""tensorBoard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlWXa_Cbk3CbsnT4cW5D8pcVy6yFKvND
"""

!pip install tensorflow
!pip install tensorboard

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir=/content/